WebApplicationYeni/Controllers/AlanController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Runtime.InteropServices;
using System.Web;
using System.Web.Mvc;
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.Concrete.Repositories;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;

namespace WebApplicationYeni.Controllers
{
    public class AlanController : Controller
    {
        public AlanBL aBl = new AlanBL(new EfAlanDal());
        public KitapBL kitapService = new KitapBL(new EfKitapDal());

        public ActionResult GetAllAlan()
        {
            Session["AlandanGelen"] = "alandan gelen session";
            var aList = aBl.GetAllAlanBl();
            return View(aList);
        }

        [Authorize(Roles = "A")]
        [HttpGet]
        public ActionResult AlanEkle()
        {
            Debug.WriteLine("AlanEkleGet cagiriliyor");
            return View();
        }

        [Authorize(Roles = "A")]
        [HttpPost]
        public ActionResult AlanEkle(Alan a)
        {
            Debug.WriteLine("AlanEkle Post cagiriliyor");
            AlanValidator alanValidator = new AlanValidator();
            ValidationResult validationResult = alanValidator.Validate(a);
            //debug icin
            Debug.WriteLine(validationResult.Errors.Count);
            if (validationResult.IsValid)
            {
                aBl.AddAlanBl(a);
                return RedirectToAction("GetAllAlan");
            }
            else
            {
                foreach (var item in validationResult.Errors)
                {
                    //fluentdeki error u System.Model deki errora ekliyoruz
                    //Sanirim bu ValidationResult kisminda System icindeki degil fluenti kullandigimiz icin
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }


        //----------------GetAlanById
        public ActionResult GetAlanById(int? id)
        {

            Debug.WriteLine("gelen id:" + id);
            Alan alan = null;
            if (id == null) return View(alan);

            int a_id = (int)id;
            alan = aBl.GetAlanByIdBl(a_id);

            if (alan == null)
            {
                Debug.WriteLine("alan null");
                return RedirectToAction("Page404", "Error");
            }
            else
            {
                Debug.WriteLine("gelen id:" + alan.AlanId + "; alanName:" + alan.AlanName);
                alan.Kitaps = kitapService.GetKitapsByAlanId(alan.AlanId);
                return View(alan);

            }

        }


        //-------------------------

        //------------Delete-----------

        //listenin üzerinden silme
        //burada yukaridaki nullable, null kontrol eklemedim, cunku liste uzerinden,
        //yani zaten olan seyler uzerinden silme seciliyor
        [Authorize(Roles = "A")]
        public ActionResult DeleteAlan(int id)
        {
            Alan alan = aBl.GetAlanByIdBl(id);
            aBl.DeleteAlanBl(alan);
            return RedirectToAction("GetAllAlan");
        }

        //--------------Update-----------------
        //GetAllAlan dan Update e yonlendirme icin
        [HttpGet]
        [Authorize(Roles = "A")]
        public ActionResult UpdateAlan(int id)
        {
            ViewData["id"] = id;

            return View();
        }

        //Guncellemek icin 
        [HttpPost]
        [Authorize(Roles = "A")]
        public ActionResult UpdateAlan(Alan a)
        {
            AlanValidator alanValidator = new AlanValidator();
            ValidationResult validationResult = alanValidator.Validate(a);
            //debug icin
            Debug.WriteLine(validationResult.Errors.Count);
            if (validationResult.IsValid)
            {
                aBl.UpdateAlanBl(a);
                return RedirectToAction("GetAllAlan");
            }
            else
            {
                foreach (var item in validationResult.Errors)
                {
                    //fluentdeki error u System.Model deki errora ekliyoruz
                    //Sanirim bu ValidationResult kisminda System icindeki degil fluenti kullandigimiz icin
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }


            ViewData["id"] = a.AlanId;
            return View();
        }

        public ActionResult AlanIstatistic()
        {
            List<Alan> list = aBl.GetAllAlanBl();
            int toplam = list.Count();
            ViewData["toplam"] = toplam;

            int grupSayisi = list.GroupBy(x => x.AlanName).Count();
            

            var linqExpress = from alan in list
                              group alan by alan.AlanName;

            ViewBag.AlanNames = linqExpress.Select(x => x.Key).ToArray();
            ViewBag.Counts = linqExpress.Select(x => x.ToList().Count()).ToArray();

            IGrouping<string, Alan> MaxGroup = linqExpress.Aggregate((a,b) => (a.ToList().Count > b.ToList().Count) ? a : b);
            int max = MaxGroup.ToList().Count;
            String maxName = MaxGroup.Key;
            
            Debug.WriteLine(linqExpress.Count());
            Debug.WriteLine(max);

            ViewData["max"] = max;
            ViewData["maxName"] = maxName;
            ViewData["buyuk10"] = linqExpress.Where(x => x.ToList().Count > 10).Count();

            return View(list);
        }



        //--------denemeler------------
        //stringQuery den alan bilgilerini alip ekleme, Alan icin tek bilgi su an Alan.AlanName
        //Su sekil bir Url ile calisir: http://localhost:51215/Alan/DenemeAlanEkle?AlanId=7&AlanName=Test
        [HttpGet]
        public ActionResult DenemeAlanEkle(Alan a)
        {
            Debug.WriteLine("AlanId:" + a.AlanId + ";AlanName:" + a.AlanName);

            aBl.AddAlanBl(a);
            return View();
        }

        //------EntityState Denemeleri Home da. Cunku buradan direkt GenericRepo ya erisilemiyor
        //sadece aBl nin repo yu kullanarak sundugu siniflara erisiliyor.

    }
}

WebApplicationYeni/Views/Alan/AlanEkle.cshtml
@using EntityLayer.Concrete
@model Alan

@{
    //Layout = "~/Views/Shared/_Layout.cshtml";
    Layout = "~/Views/Shared/_LayoutLeftBar.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AlanEkle</title>
</head>
<body>
    <h3>Alan Ekleme</h3>
    
    <div>
        @using (Html.BeginForm("AlanEkle", "Alan", FormMethod.Post))
        {
            <div class="form-group">
                @Html.Label("Alan Adi")
                @Html.TextBoxFor(x=>x.AlanName, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.AlanName)
                <br /> <br />
                <button class="btn btn-secondary">Ekle</button>
            </div>
        }

    </div>


</body>
</html>

WebApplicationYeni/Views/Alan/AlanEkleFalse.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>View</title>
</head>
<body>
    <p>alan adini kucuk harflerden olusan tek kelime olarak girin</p>
    <div> 
    </div>
</body>
</html>

WebApplicationYeni/Views/Alan/AlanIstatistic.cshtml
@using EntityLayer.Concrete
@model List<Alan>

@{
    ViewBag.Title = "AlanIstatistic";
    Layout = "~/Views/Shared/_LayoutLeftBar.cshtml";
}

@*@ViewData["buyuk10"]*@
<h3>Alan ile İlgili İstatistikler</h3>

@foreach (string AlanName in ViewBag.AlanNames)
{
    <p>@AlanName</p>
}

@foreach (int AlanName in ViewBag.)
{
    <p>@AlanName</p>
}

<br />

<table class="table table-bordered">
    <tr>
        <th>Toplam Alan Sayisi</th>
        <td>@ViewData["toplam"]</td>
    </tr>
    <tr>
        <th>En cok bulunan Alanin adi</th>
        <td>@ViewData["maxName"]</td>
        <th>En cok bulunan Alanin sayisi</th>
        <td>@ViewData["max"]</td>
    </tr>



</table>

WebApplicationYeni/Views/Alan/DenemeAlanEkle.cshtml
@{
    ViewBag.Title = "DenemeAlanEkle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>DenemeAlanEkle</h2>

WebApplicationYeni/Views/Alan/GetAlanById.cshtml
@model EntityLayer.Concrete.Alan

@{
    Layout = "~/Views/Shared/_LayoutLeftBar.cshtml";

}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>GetAlanById</title>
</head>

<body>
    @*gormek istediginiz alanin Id sini girin
        <form method="get">
            <input type="number" name="id">
            <button>getir</button>
        </form>*@
    <div class="container pt-4">
        <h3>@Model.AlanName</h3>

        @if (Model == (null))
        {
            <p> Verdiginiz Id de bir alan bulunamadi </p>
        }
        else
        {
            <table class="table table-bordered">
                <tr>
                    <th>Kitap Id</th>
                    <th>Kitap Adı</th>
                    <th>Yazar Adı</th>
                </tr>
                @foreach (EntityLayer.Concrete.Kitap k in Model.Kitaps)
                {
                    <tr>
                        <td>@k.KitapId</td>
                        <td>@k.KitapName</td>
                        <td>@k.Yazar.YazarName</td>
                    </tr>
                }
            </table>

        }
    </div>






</body>
</html>


@*@using (Html.BeginForm("GetAlanById", "Alan", FormMethod.Post))
    {
        <div class="form-check">
            @Html.Label("Id")
            @Html.TextBoxFor(x => x.AlanName)
            <br />
            <button>getir</button>
        </div>
    }*@

WebApplicationYeni/Views/Alan/GetAllAlan.cshtml
@{
    //Layout = "~/Views/Shared/_Layout.cshtml";
    Layout = "~/Views/Shared/_LayoutLeftBar.cshtml";
    var userRole = (string)Session["Role"];
    string color = "";
}

@using EntityLayer.Concrete
@model List<Alan>

<!DOCTYPE html>


<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <title>GetAllAlan</title>
</head>
<body>

    <h3>Alanlar</h3>
    @Html.Label("Alan sayısı")
    @Model.Count
    
    <table class="table table-bordered">
        <tr>
            <th>AlanId</th>
            <th>AlanName</th>
            <th>Kitaplar</th>
            @if ("A" == userRole)
            {
                <th>Sil</th>
                <th>Güncelle</th>
                <th>Kitap Ekle</th>
            }


        </tr>
        @foreach (Alan a in Model)
        {

            <tr>
                <td>@a.AlanId</td>
                <td>@a.AlanName</td>
                <td><a href="~/Alan/GetAlanById?id=@a.AlanId" class="btn btn-warning">Kitapları</a></td>
                @if ("A" == userRole)
                {
                    <td><a href="DeleteAlan/@a.AlanId" class="btn btn-danger">sil</a></td>
                    <td><a href="UpdateAlan?id=@a.AlanId" class="btn btn-outline-info">Güncelle</a></td>
                    <td><a href="~/Kitap/KitapEkle?AlanId=@a.AlanId&AlanName=@a.AlanName" class="btn btn-outline-primary">KitapEkle</a></td>
                }

            </tr>
        }
    </table>

</body>
</html>

WebApplicationYeni/Views/Alan/UpdateAlan.cshtml
@model EntityLayer.Concrete.Alan


@{
    ViewBag.Title = "UpdateAlan";
    //Layout = "~/Views/Shared/_Layout.cshtml";
    Layout = "~/Views/Shared/_LayoutLeftBar.cshtml";
}

<h3>Alan Güncelleme</h3>

@using (Html.BeginForm("UpdateAlan", "Alan", FormMethod.Post))
{
    @Html.Label("AlanId")
    <input tpye="number" name="AlanId" value="@ViewData["id"]" class="form-control" readonly>

    <br />
    @Html.Label("AlanName")
    @*@Html.DropDownListFor(x => x.AlanId, (List<SelectListItem>) ViewBag.Alist, new { @class = "form-control" })*@

    @Html.TextBoxFor(x => x.AlanName, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.AlanName)
    <br />
    <button class="btn btn-secondary">güncelle</button>
}