WebApplicationYeni/Controllers/KitapController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessLayer.Abstract;
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
 
namespace WebApplicationYeni.Controllers
{
    public class KitapController : Controller
    {
        IKitapService kitapBl;
        //kaldırılabilir
        IYazarService yazarBl;
        IAlanService alanBl;


        public KitapController()
        {
            kitapBl = new KitapBL(new EfKitapDal());
            yazarBl = new YazarBL(new EfYazarDal());
            alanBl = new AlanBL(new EfAlanDal());
        }

        [Authorize]
        public ActionResult GetAllKitaps()
        {
            List<Kitap> kitaps = kitapBl.GetAllKitapsBl();
            return View(kitaps);
        }

        
        [Authorize(Roles = "A")]
        public ActionResult KitapEkle(Alan a)
        {
            //Alanlar icin drop down liste gonderilecek list
            List<SelectListItem> alans = (from x in alanBl.GetAllAlanBl()
                                         select new SelectListItem
                                         {
                                             Text = x.AlanName,
                                             Value = x.AlanId.ToString()
                                         }).ToList();
            ViewBag.Dlist = alans;

            return View(a);
        }



        //KitapEkle async deneme
        //kitapDosya.SaveAs(...) diske dosyayı yazma işlemi
        //Bunun async olmasi lazim sanirim?
        [Authorize(Roles = "A")]
        [HttpPost]
        public ActionResult KitapEkle(Kitap k, HttpPostedFileBase kitapDosya)
        {

            Yazar y = yazarBl.GetYazarBl(k.Yazar);
            if (null == y)
            {
                Debug.WriteLine("Girdiginiz yazar daha onceden eklenmemis");
                ViewBag.Message = "Yeni yazar olusturuldu";
            }
            else
            {
                k.YazarId = y.YazarId; //k.Yazar = y; 
                k.Yazar = null;

            }

            k.KitapStatus = true;

            HttpPostedFileWrapper httpPostedFileWrapper = null;
            //sonradan ekledigim kitap dosyasi islemleri
            //--------------------------
            //kitapDosya icin bir sey gondermezsen sıkıntı yok, demekki null olabilen bir tür
            if (kitapDosya != null)
            {
                //Normalde Abstract Class olan kitapDosya icin MVC icindeki ModelBinder hangi class ı atıyor
                Debug.WriteLine("Tip: " + kitapDosya.GetType().FullName);

                Debug.WriteLine("kitapDosya türü:" + kitapDosya.GetType());
                Debug.WriteLine("KitapDosya var, kitapDosya.FileName:" + kitapDosya.FileName);
                Debug.WriteLine("Uzunluk:" + kitapDosya.ContentLength);
                string dosyaYolu = Path.GetFileName(kitapDosya.FileName);
                string kitapYolu = String.Format("/Dosyalar/{0}", dosyaYolu);
                Debug.Write(dosyaYolu);
                var yuklemeYeri = Path.Combine(Server.MapPath("~/Dosyalar"), dosyaYolu);
                Debug.WriteLine("dosyaYolu:" + dosyaYolu);
                Debug.WriteLine("kitapYolu:" + kitapYolu);
                Debug.WriteLine("yuklemeYeri:" + yuklemeYeri);
                try
                {
                    kitapDosya.SaveAs(yuklemeYeri);
                    k.KitapYolu = kitapYolu;
                }
                catch (Exception e)
                {
                    Debug.WriteLine("Exception atıldı hooppp");
                    return RedirectToAction("GetAllKitaps");
                }

            }

            //--------------------------

            kitapBl.KitapEkleBl(k);


            return RedirectToAction("GetAllKitaps");
        }





        public ActionResult getKitapDosyaById(int id)
        {
            Debug.WriteLine("id:" + id);
            Kitap k = kitapBl.GetKitapByIdBl(id);
            Debug.WriteLine("Kitap id:" + k.KitapId);
            Debug.WriteLine("Kitap Yolu:" + k.KitapYolu);
            ViewBag.kitapYolu = k.KitapYolu;
            return View();
        }


        //belli bir yazarin id sini alip onun kitaplarini getirme
        public ActionResult GetKitapsByYazarId(int yazarId)
        {
            return View("GetAllKitaps", kitapBl.GetKitapsByIdBl(yazarId));
        }


        [Authorize(Roles = "A")]
        [HttpGet]
        public ActionResult UpdateKitap(int id)
        {   
            return View(kitapBl.GetKitapByIdBl(id));
        }

        [Authorize(Roles = "A")]
        [HttpPost]
        public ActionResult UpdateKitap(Kitap k, HttpPostedFileBase kitapDosya)
        {
            //k.Yazar null ise duzgun calisiyor, degilse Id lerinin esit olmasini istiyor,(k.YazarId ve k.Yazar.YazarId)
            if (k.Yazar == null) Debug.WriteLine("k.Yazar null");
            else
            {
                Debug.WriteLine("k.YazarId" + k.YazarId);
                Debug.WriteLine("k.Yazar.YazarId" + k.Yazar.YazarId);
                Debug.WriteLine("k.Yazar.YazarName" + k.Yazar.YazarName);
                Debug.WriteLine("k.Yazar.YazarDTarih" + k.Yazar.YazarDTarih);
            }

            Yazar y = yazarBl.GetYazarBl(k.Yazar);
            if(null == y)
            {
                Debug.WriteLine("Girdiginiz kriterlerde bir yazar bulunamadi, yazar ekleniyor");
                yazarBl.AddYazarBl(k.Yazar);
                y = yazarBl.GetYazarBl(k.Yazar);
                if(null == y) Debug.WriteLine("Eklenen yazar cekilemedi");
                k.YazarId = y.YazarId;
            }
            Debug.WriteLine("y.YazarId" + y.YazarId);
            Debug.WriteLine("y.YazarName" + y.YazarName);
            Debug.WriteLine("y.YazarDTarih" + y.YazarDTarih);
            k.Yazar = y;

            //file islemi
            if (kitapDosya != null)
            {
                Debug.WriteLine("kitapDosya türü:" + kitapDosya.GetType());
                Debug.WriteLine("KitapDosya var, kitapDosya.FileName:" + kitapDosya.FileName);
                Debug.WriteLine("Uzunluk:" + kitapDosya.ContentLength);
                string dosyaYolu = Path.GetFileName(kitapDosya.FileName);
                string kitapYolu = String.Format("/Dosyalar/{0}", dosyaYolu);
                Debug.Write(dosyaYolu);
                var yuklemeYeri = Path.Combine(Server.MapPath("~/Dosyalar"), dosyaYolu);
                Debug.WriteLine("dosyaYolu:" + dosyaYolu);
                Debug.WriteLine("kitapYolu:" + kitapYolu);
                Debug.WriteLine("yuklemeYeri:" + yuklemeYeri);
                try
                {
                    kitapDosya.SaveAs(yuklemeYeri);
                    k.KitapYolu = kitapYolu;
                }
                catch (Exception e)
                {
                    Debug.WriteLine("Exception atıldı hooppp");
                    return RedirectToAction("GetAllKitaps");
                }

            }

            kitapBl.UpdateKitapBl(k);
            return RedirectToAction("GetAllKitaps");
        }

        [Authorize(Roles = "A")]
        public ActionResult DeleteKitap(int id)
        {
            Kitap k = kitapBl.GetKitapByIdBl(id);
            k.KitapStatus = false;
            kitapBl.DeleteKitapBl(k);
            return RedirectToAction("GetAllKitaps");
        }

        public PartialViewResult PartialDeneme()
        {
            return PartialView();
        }

        public ActionResult KitapIstatistic()
        {

            return View();
        }

        //KitapIstatisticler icin chart
        public PartialViewResult KitapChart() 
        {
            var linqExpression = from k in kitapBl.GetAllKitapsBl()
                                 group k by k.Alan.AlanName;

            ViewBag.xValues = linqExpression.Select(x => x.Key).ToArray();
            ViewBag.yValues = linqExpression.Select(x => x.ToList().Count).ToArray();

            return PartialView();
        }

        
      
    }
}

WebApplicationYeni/Controllers/YazarController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessLayer.Abstract;
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;

namespace WebApplicationYeni.Controllers
{
    public class YazarController : Controller
    {
        IYazarService yazarService;
        public YazarController()
        {
            yazarService = new YazarBL(new EfYazarDal());
        }

        public ActionResult GetAllYazar() 
        { 
            return View(yazarService.GetAllYazarBl());
        }

        [HttpGet]
        [Authorize(Roles = "A")]
        public ActionResult YazarEkle()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "A")]
        public ActionResult YazarEkle(Yazar y)
        {
            Debug.WriteLine("yazarId:" + y.YazarId);
            Debug.WriteLine("yazarName:" + y.YazarName);
            Debug.WriteLine("yazarDTarih:" + y.YazarDTarih);

            yazarService.AddYazarBl(y);
            return RedirectToAction("GetAllYazar");
        }

        [Authorize(Roles = "A")]
        public ActionResult DeleteYazar(int id)
        {
            yazarService.DeleteYazarBl(yazarService.GetYazarByIdBl(id));
            return RedirectToAction("GetAllYazar");
        }


        [Authorize(Roles = "A")]
        public ActionResult UpdateYazar(int id)
        {
            //ViewData["id"] = id;
            return View(yazarService.GetYazarByIdBl(id));
        }

        [HttpPost]
        [Authorize(Roles = "A")]
        public ActionResult UpdateYazar(Yazar y)
        {
            Debug.WriteLine("yazarID" + y.YazarId);
            yazarService.UpdateYazarBl(y);
            return RedirectToAction("GetAllYazar");
        }


        //Acaba getById gibi bir methodla silinmek istenen nesne çekilmeden de silme islemi gerceklestirilebiliyor mu?
        //Yani istenen id nin oldugu bir nesne verilsin genericRepo ya yeter mi? Evet
        //GenericRepo sadece id ye gore db ye bir sorgu atıyor olabilir?
        public void DeleteYazar2(int id)
        {
            Yazar yazar = new Yazar();
            yazar.YazarId = id;
            yazarService.DeleteYazarBl(yazar);
            
        }
    }
}

WebApplicationYeni/Views/Kitap/EklenenKitap.cshtml
@using EntityLayer.Concrete
@model Kitap
@{
    ViewBag.Title = "EklenenKitap";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>EklenenKitap</h2>
<p>@ViewBag.Message</p>

<table>
    <tr>
        
        <th>KitapName</th>
        <th>AlanId</th>
        <th>YazarId</th>

    </tr>
    <tr>

        <td>@Model.KitapName</td>
        <td>@Model.AlanId</td>
        @*<td>@Model.YazarId</td>
        <td>@Model.Yazar.YazarName</td>
        <td>@Model.Yazar.YazarDTarih</td>*@


    </tr>
</table>

WebApplicationYeni/Views/Kitap/GetAllKitaps(Eski).cshtml
@using EntityLayer.Concrete
@model List<Kitap>

@{
    ViewBag.Title = "GetAllKitaps";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>GetAllKitaps</h2>

<table class="table table-bordered">
    <tr>
        <th>KitapId</th>
        <th>KitapName</th>
        <th>YazarId</th>
        <th>AlanId</th>
        <th>AlanName</th>
        <th>Status</th>
        <th>Guncelle</th>
        <th>Sil</th>


    </tr>
    @Html.Label("Kitap Sayisi")
    @Model.Count



    @foreach (Kitap k in @Model)
    {
        string color = "";
        if (k.KitapStatus == false) { color = "red"; }
        else { color = "green"; }

        <tr>
            <td>@k.KitapId</td>
            <td>@k.KitapName</td>
            <td>@k.YazarId</td>
            <td>@k.AlanId</td>
            <td>@k.Alan.AlanName</td>
            <td style="color:@color">@k.KitapStatus</td>
            @* <td><a href="UpdateKitap?id=@k.KitapId" class="btn btn-info">guncelle</a></td>*@

            <td><a class="btn btn-info" data-toggle="modal" data-target="#Modal1">guncelle</a></td>


            <td><a href="DeleteKitap/@k.KitapId" class="btn btn-danger">sil</a></td>
        </tr>
    }

</table>

@*<button class="btn btn-info" data-bs-toggle="modal" data-target="#Modal1">popup</button>


<div class="modal" id="Modal1">

</div>*@

@*@Html.Action("GetAllYazar", "Yazar")*@

WebApplicationYeni/Views/Kitap/GetAllKitaps.cshtml
@{
    ViewBag.Title = "GetAllKitaps";
    Layout = "~/Views/Shared/_LayoutLeftBar.cshtml";
    //string userRole = (string)Session["Role"];
    FormsAuthenticationTicket fat = FormsAuthentication.Decrypt(Request.Cookies.Get(".ASPXAUTH").Value);
    string userRole = fat.UserData;

    string color = "";
}


@using EntityLayer.Concrete
@model List<Kitap>
@*admin rol:@Session["Role"]
username:@Session["AdminUserName"]*@

<h3>Kitaplar</h3>

<table class="table table-bordered">
    <tr>
        <th>KitapId</th>
        <th>KitapName</th>
        <th>YazarId</th>
        <th>YazarAdı</th>

        <th>AlanId</th>
        <th>Alan Adı</th>
        <th>Yorumlar</th>
        @if (userRole == "A")
        {
            <th>Status</th>
            <th>Güncelle</th>
            <th>Sil</th>
        }



    </tr>
    @*@Html.Label("Kitap Sayısı")
    @Model.Count
    @Session["AdminUserName"]
    @Session["AlandanGelen"]*@


    @foreach (Kitap k in @Model)
    {
        if (k.KitapStatus == false) { color = "red"; }
        else { color = "green"; }
        if (k.KitapStatus == true | (userRole == "A"))
        {

            <tr>
                <td>@k.KitapId</td>
                <td><a href="~/Kitap/getKitapDosyaById/@k.KitapId">@k.KitapName</a></td>
                <td>@k.YazarId</td>
                <td>@k.Yazar.YazarName</td>
                <td>@k.AlanId</td>
                <td>@k.Alan.AlanName</td>
                <td><a href="~/Comment/getCommentsById/@k.KitapId" class="btn btn-warning">Yorumlar</a></td>


                @if (userRole == "A")
                {
                    <td style="color:@color">@k.KitapStatus</td>
                    <td><a href="Kitap/UpdateKitap?id=@k.KitapId" class="btn btn-info">Güncelle</a></td>
                    <td><a href="Kitap/DeleteKitap/@k.KitapId" class="btn btn-danger">Sil</a></td>
                }

            </tr>
        }



    }

</table>


@*@foreach (Kitap k in @Model)
    {
        //string color = "";
        //if (k.KitapStatus == false) { color = "red"; }
        //else { color = "green"; }


        <tr>
            <td>@k.KitapId</td>
            <td>@k.KitapName</td>
            <td>@k.YazarId</td>
            <td>@k.AlanId</td>
            <td>@k.Alan.AlanName</td>
            <td><a href="~/Comment/getCommentsById/@k.KitapId" class="btn btn-warning">Yorumlar</a></td>


            @if (userRole == "A")
            {
                <td style="color:@color">@k.KitapStatus</td>
                <td><a href="Kitap/UpdateKitap?id=@k.KitapId" class="btn btn-info">Güncelle</a></td>
                <td><a href="Kitap/DeleteKitap/@k.KitapId" class="btn btn-danger">Sil</a></td>
            }

        </tr>
    }*@

WebApplicationYeni/Views/Kitap/KitapChart.cshtml
@{
    var myChart = new Chart(width: 600, height: 600)
        .AddTitle("Kitaplar")
        .AddSeries(
            name: "Employee",
            xValue: ViewBag.xValues,
            yValues: ViewBag.yValues)
        .Write();
}


@*@{
        var myChart = new Chart(width: 600, height: 400)
            .AddTitle("Chart Title")
            .AddSeries(
                name: "Employee",
                xValue: new[] { "Peter", "Andrew", "Julie", "Mary", "Dave" },
                yValues: new[] { "2", "6", "4", "5", "3" })
            .Write();
    }*@

WebApplicationYeni/Views/Kitap/KitapEkle.cshtml
@using EntityLayer.Concrete
@model Alan

@{
    ViewBag.Title = "KitapEkle";
    Layout = "~/Views/Shared/_LayoutLeftBar.cshtml";
}

@{
    var date = DateTime.Now;
    var formattedDate = $"{date:yyyy-MM-ddTHH:mm}";
}

<div class="container pt-4 mb-3">
    <h3>Kitap Ekle</h3>

    <form action="KitapEkle" method="post" enctype="multipart/form-data">
        @Html.Label("AlanId")
        @Html.DropDownListFor(x => x.AlanId, (List<SelectListItem>)ViewBag.Dlist, new { @class = "form-control" })

        @*@Html.Label("AlanName")
        <input name="Alan.AlanName" value="@Model.AlanName" readonly />*@

        @Html.Label("YazarAdı")
        <input type="text" name="Yazar.YazarName" class="form-control" />

        @Html.Label("YazarDogumTarih")
        <input type="datetime-local" name="Yazar.YazarDTarih" value="@formattedDate" class="form-control w-25" />

        @Html.Label("KitapAdı")
        <input type="text" name="KitapName" class="form-control" />

        @Html.Label("Kitap Dosyası")
        <input type="file" name="kitapDosya" class="form-control-file" />

        <button class="btn btn-outline-primary mt-3">Ekle</button>
    </form>
</div>

WebApplicationYeni/Views/Kitap/KitapIstatistic.cshtml
@{
    ViewBag.Title = "KitapIstatistic";
    Layout = "~/Views/Shared/_LayoutLeftBar.cshtml";
}

<h3>Kitap İstatistikleri</h3>
@Session["AdminUserName"]



<p><img src="KitapChart"/> </p>

WebApplicationYeni/Views/Kitap/PartialDeneme.cshtml
merhaba

WebApplicationYeni/Views/Kitap/UpdateKitap.cshtml
@model EntityLayer.Concrete.Kitap


@{
    ViewBag.Title = "kitapGuncelle";
    Layout = "~/Views/Shared/_LayoutLeftBar.cshtml";

    var date = Model.Yazar.YazarDTarih;
    var formattedDate = $"{date:yyyy-MM-ddTHH:mm}";
}



<div class="container pt-4 mb-3">
    <h3>Kitap Guncelle</h3>

    <form action="UpdateKitap" method="post" enctype="multipart/form-data">
        @Html.Label("Kitap Id")
        <input name="KitapId" value="@Model.KitapId" class="form-control" readonly />

        @Html.Label("Kitap Adı")
        <input name="KitapName" type="text" value="@Model.KitapName" class="form-control" />

        @Html.Label("Kitap Dosyası")
        <input type="file" name="kitapDosya" class="form-control-file" />

        @Html.Label("AlanId")
        <input name="AlanId" value="@Model.AlanId" class="form-control" readonly />

        @Html.Label("Alan Adı")
        <p class="form-control">@Model.Alan.AlanName</p>

        @Html.Label("YazarId")
        <input name="YazarId" value="@Model.YazarId" class="form-control" />

        @Html.Label("Yazar Adı")
        <input type="text" name="Yazar.YazarName" value="@Model.Yazar.YazarName" class="form-control" />

        @Html.Label("Yazar Doğum Tarihi")
        <input type="datetime-local" name="Yazar.YazarDTarih" value="@formattedDate" class="form-control w-25" />

        <button class="btn btn-outline-primary mt-3">Guncelle</button>
    </form>
</div>

WebApplicationYeni/Views/Kitap/getKitapDosyaById.cshtml
@{
    ViewBag.Title = "getKitapDosyaById";
    Layout = "~/Views/Shared/_LayoutLeftBar.cshtml";
    string kitapYolu = (string)@ViewBag.kitapYolu;
}

<h3>Kitap Dosyası</h3>
kitapYolu

<iframe src="@kitapYolu" type="application/pdf" width="600" height="800" /></iframe>
@*<iframe src="@ViewBag.kitapYolu" type="application/pdf" width="300" height="600" />*@